# LDPC codes (tutorial)
## M.Sc. Vladimir Fadeev
### Kazan, 2021

## Block codes encoding basics 

LDPC codes are linear block codes, which means that the *check bits* are added at the end of information messages  (as a block).

The encoding procedure is the multiplication of message vector and Generator matrix:

$$ \underset{1\times N} {\mathbf{a}} = \underset{1\times K} {\mathbf{u}} \otimes  \underset{K\times N} {\mathbf{G}}\qquad (1)  $$

where $ \mathbf{u} $ is the input message, and $ \mathbf{a} $ is the code word, $\otimes$ denotes multiplication by modulo $q$, where $q$ is a Galois Field parameter: $GF(q = 2^p)$ (obviously, for binary case $q$ is equal to 2).

Accordingly, the code rate is also specified via the generating matrix:

<img src="https://habrastorage.org/webt/jq/im/zq/jqimzqtfegyfgbce2h9wqr6gswg.png" width="800" />

Generator matrix consists of two contatenated matrices:

$$ \underset{K\times N} {\mathbf{G}} = \left[ \underset{K\times K} {\mathbf{I}} \qquad  \underset{K\times (N-K)} {\mathbf{-P}}\right] \qquad (2)$$

where $\mathbf{P}$ is the *parity part*, and $ \mathbf{I} $ is the *identity matrix*. Note, the **identity part** is needed to keep the code **systematic**: the information message remains unchanged, and the check bits are added to the end of the block. A correctly restored codeword can restore the original message by simply removing the checked bits. Convenient, isn't it?

Since we are talking about **linear block codes**, the generator matrix should provide this linearity (see. [Linear code](https://en.wikipedia.org/wiki/Linear_code#:~:text=In%20coding%20theory%2C%20a%20linear,hybrid%20of%20these%20two%20types.)). This means that the rows of the generator matrix must be **linearly independent** (yes, it sounds a little paradoxical).

The generator matrix is directly related to another important matrix, which used in decoding procedure: **Parity Check matrix**. Parity-check matrix has $(N−K)$ rows and $N$ columns, where $N$ corresponds to desired length of codeword and $K$ corresponds to the length of the message:

$$ \underset{(N-K)\times N} {\mathbf{H}} = \left[ \underset{(N-K)\times K} {\mathbf{P}^T} \qquad  \underset{(N-K)\times (N-K)} {\mathbf{I}}\right] \qquad(3)$$

The main idea can be well explained via the [Tanner graph](https://en.wikipedia.org/wiki/Tanner_graph#Tanner_graphs_for_linear_block_codes):

![](https://habrastorage.org/webt/7c/l-/ub/7cl-ubcrityadm0k5s_bbktdjso.png)

There are two types of nodes: 
- **variable nodes**, the number of which correspond to the number of columns $K$, and 
- **check nodes**, corresponding to the number of rows $(N - K)$. 

The nodes are interconnected, and the relationship is determined by the position of units in the matrix $\mathbf{H}$. 

The picture on the right is my own mnemonics of my own production. It seems to me that this is the easiest way to catch the essence of the structure: 
- if the matrix element is 1, then there is a connection between nodes, 
- if it is 0, there is no connection.

In order to consider the decoding procedure successful, it is necessary that certain values are formed on all test nodes - as a rule, zeros (see [decoding based on syndromes](https://en.wikipedia.org/wiki/Decoding_methods#Syndrome_decoding)):

$$ \mathbf{s} = \mathbf{H}\mathbf{x} = \mathbf{0} \qquad(4)$$

Actually, this matrix defines the last two letters in the abbreviation LD**PC** (Parity-Check).

## LDPC encoding basics

But all of the above are common points for most of block codes. How then are LDPCs different from the, for example, Hamming codes?


In general, by what defines them as **low-density**: their parity check matrices must be sparce:

> "Low density parity check codes are codes specified by a parity check matrix containing mostly zeros and only small number of ones." [\[1\]](https://dspace.mit.edu/bitstream/handle/1721.1/11804/32786367-MIT.pdf?sequence=2)

Yes, that’s so simple.


For example, **Gallagher** have proposed this matrix:

<img src="https://habrastorage.org/webt/ed/cz/nt/edczntggcntmubzhbuom6iq4tgo.png" width="400" />

**(3,4)** - **regular** parity check matrix with a length of 12. 

Explanation: 
- a codeword that will be encoded using code which based on this matrix will have a length of 12 bits; 
- there are 3 ones in each column, and there 4 ones in each row (hence (3,4)); 
- the number of ones in rows and columns are constants (in our case 3 and 4), which means the code is regular.

**Mackay and Neal** described a parity check matrix like this:

<img src="https://habrastorage.org/webt/gc/ce/l4/gccel4srlihwulfcj57tctazt24.png" width="400" />

**(3,4)** - **regular** parity check matrix with a length of 12. 

> **NOTE**:
>
> In the DVB-S2 standard **irregular** parity check matrices are used:
>
> *Eroz M., Sun F. W., Lee L. N. [DVB‐S2 low density parity check codes with near Shannon limit performance](http://www.iet.unipi.it/m.luise/DVB-S2_Low-Density.pdf) //International Journal of Satellite Communications and Networking. – 2004. – Т. 22. – №. 3. – С. 269-279.*
>
> This corresponds to better noise immunity of irregular codes.

However, you don’t notice anything? That's right: these matrices do not fall under the standard form from formula (3), because for LDPC codes we strive to make check matrices sparse. And if the verification matrices do not fall into the standard form, then it is not entirely clear how to generate generating matrices for them.


The answer, of course, is (and not one). Suppose this: the original matrix $\mathbf{H}$ is brought to the standard form using the Gaussian elimination method, the generating matrix is obtained from the standard form, and it is used for encoding.



## Example

Here is an example from this teaching material:

> Johnson, S. J. (2006). [Introducing low-density parity-check codes](https://www.researchgate.net/publication/228977165_Introducing_Low-Density_Parity-Check_Codes). University of Newcastle, Australia, V1.

Let us start from the following matrix $\mathbf{H}$:

In [1]:
import numpy as np

H = np.array([[1, 1, 0, 1, 1, 0, 0, 1, 0, 0],\
              [0, 1, 1, 0, 1, 1, 1, 0 ,0 ,0],\
              [0, 0, 0, 1, 0, 0, 0, 1, 1, 1],\
              [1, 1, 0, 0, 0, 1, 1, 0, 1, 0],\
              [0, 0, 1, 0, 0, 1, 0, 1, 0, 1]])

From this, by moving and transforming the rows by modulo 2, as well as moving the columns, we moved to the matrix $\mathbf{H}_{std}$:

In [2]:
Hstd = np.array([[0, 1, 1, 1, 0, 1, 0, 0, 0, 0],\
                 [1, 0, 1, 0, 0, 0, 1, 0 ,0 ,0],\
                 [1, 0, 1, 0, 1, 0, 0, 1, 0, 0],\
                 [0, 0, 1, 1, 1, 0, 0, 0, 1, 0],\
                 [1, 1, 0, 0, 1, 0, 0, 0, 0, 1]])

<img src="https://habrastorage.org/webt/as/2o/6g/as2o6g0cu6wtesk41xcbuegbgke.png" width="500"/>

Transformations with rows from the point of view of linear algebra do not affect the code word, but column movements need to be remembered:

In [3]:
idx = [5, 6, 7, 8, 9, 0, 1, 2, 3, 4]

Then form the generating matrix:

In [4]:
M = np.shape(H)[0] # N-K
N = np.shape(H)[1] 
K = N - M

G = np.concatenate([np.eye(K), ((-1)*Hstd[:, :K].T %2)], axis=1)
print("Generator matrix:\n %s" % str(G))

Generator matrix:
 [[1. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 1. 1.]]


<img src="https://habrastorage.org/webt/5g/u9/d6/5gu9d67jx3onkhfkaz527xfcqjg.png" width="400" />

Create a codeword:

In [5]:
c = np.array([1, 0, 1, 0, 1]) @ G %2
print(str(c))

[1. 0. 1. 0. 1. 1. 0. 1. 0. 0.]


And we check the syndrome (that is, we encoded the word with a matrix derived from $\mathbf{H}_{std}$, and in the decoding process we will use the sparse matrix $\mathbf{H}$):

In [6]:
c[idx] @ H.T %2

array([0., 0., 0., 0., 0.])

The magic of linear algebra works!

Concluding the section, it must be said that such a coding method is the easiest to understand, but very difficult to calculate in the case of large matrices - the generating matrix, as a rule, ceases to be discharged. Of course, all this has its own decisions, however, this is a completely different story...

## LDPC decoding: Sum-product algorithm

A lot of decoding algorithms exist for the LDPC codes, but we will consider well-known **sum-product algorithm** (SPA or belief propagation algorithm) [\[3, p.31\]](https://www.researchgate.net/publication/228977165_Introducing_Low-Density_Parity-Check_Codes) with some references to matrix representation during this work. 

First of all, assume that from the channel we have some noisy values that can be represented as soft values after demodulation - Loglikelihood ratios (LLRs):

$$
r = \ln \left( \frac{p(x=0)}{p(x=1)}\right)  = \ln \left(\frac{1 - p}{p} \right) \qquad (4)
$$

where $p$ denotes probability and $x$ denotes some event.

Actually, the decoding procedure can be imagined as transfer of certain probabilities from Variable nodes to Check nodes (V2C message) and vice versa (C2V message). At the first step LLRs correspond to *a priori probabilities*. The SPA aims to maximaze *a posteriori probabilities*, hence the SPA is one of the maximum a posteriori probability (MAP) algorithms.  

### The first iteration (initialization)

The initial point for **V2C** message at the first iteration is the one-rank matrix of the LLRs: 

$$
\underset{M\times N} {\mathbf{M}} = \left(\underset{N\times 1} {\mathbf{r}} \cdot \underset{1\times M} {\mathbf{1}} \right)^T  \odot \underset{M\times N} {\mathbf{H}} \qquad (5)
$$

where $\mathbf{1}$ is the matrix or vector of ones, and $\odot$ denotes Hadamard (element-wise) product. 

> **NOTE #1:**
> 
> One-rank matrix can be replaced by the iterative Hadamard multiplication of the LLR's vector and columns of Parity-Check matrix (additional loop).  

### Variable-to-Check message

Then algorithm requires to process **V2C** message in probability domain using relation between [hyperbolic tangents](http://wwwf.imperial.ac.uk/metric/metric_public/functions_and_graphs/hyperbolic_functions/inverses.html) and natural logarithm [\[3, p.32\]](https://www.researchgate.net/publication/228977165_Introducing_Low-Density_Parity-Check_Codes). Procedure of transmission **V2C** message is multiplication (for probabilities) of non-zero elements in each row:

$$ E_{j,i} = log \left( \frac{1 + \prod_{i'\epsilon B_j, i' \neq i} tanh(M_{j,i'}/2)}{1 - \prod_{i'\epsilon B_j, i' \neq i} tanh(M_{j,i'}/2)} \right) = log \left( \frac{1 + \prod_{i'\epsilon B_j, i' \neq i} M'_{j,i'}}{1 - \prod_{i'\epsilon B_j, i' \neq i} M'_{j,i'}} \right) \qquad(7)$$

where $j$ is the number of the certain row, $i$ is the number of the certain column,   $B_{j}$ is the set of the non-zero elements in $j$-th row, and $i'\neq i$ means that we exlude $i$-th variable node from the consideration.

<img src="https://habrastorage.org/webt/ig/ub/jn/igubjn0ixl-zjjok4l3kz2yoo5y.png" width="500"/>

*Fig. 2. The illustration of the V2C message passing.*

> **NOTE #2:**
>
> To reduce number of condition checks (such as: zero or non-zero element, i-th element or not) the following mathematical hint can be used:
>
> 1) Replace all of the corresponding to Parity-Check matrix structure zeros by ones: 
> $$ \mathbf{M}'' =  \mathbf{M}' + \mathbf{H}'  $$
> where $\mathbf{H}' = \mathbf{H}+ \mathbf{1}$ is the "mirror" of the Parity-Check matrix
>
> 2) Multiply all of the elements and divide the result by the $i$-th element:
> $$ E_{j,i}' = log \left( \frac {1 + \frac{1}{M"_{j,i}} \prod_{i} M''_{j,i}} {1 - \frac{1}{M"_{j,i}} \prod_{i} M''_{j,i}} \right)  $$
>
> 3) Keep the structure of the Parity-Check matrix:
> $$ \mathbf{E} = \mathbf{E}' \odot \mathbf{H} $$
> 
> This solution can be appropriate for the small study modeling tasks, however, additional calculations may significantly increase simulation time for the large Parity-Check matrices.

### Check-to-Variable message

At the end of the first iteration the LLRs from the channel should be updated. For this purpose we sum up the information of rows in matrix $\mathbf{E}$.

$$
l_i = r_i + \sum_{j\epsilon A_i}E_{j,i} \qquad(8)
$$

where $A_i$ is the set of the coresponding to Parity-Check matrix non-zero elements in $i$-th column. 

> **NOTE #3:**
>
> The summation of all of the column elements can be applied with the same mathematical sense since the zero-elements do not contribute to the addition. 
> $$ \mathbf{l} = \mathbf{r} + \left(\sum\mathbf{E}_{j}\right)^T $$
> The same problems may occure as in the **Note #2**.

After that we map up-to-date LLRs to binary symbol by the rule:

$$
z_i = 
\begin{cases}
0 &\text{if $l_i \geq 0$}\\
1 &\text{if $l_i < 0$}
\end{cases} \qquad(9)
$$

Then necessary condition should be checked:

$$
\underset{M\times 1} {\mathbf{s}} = \underset{M\times N} {\mathbf{H}} \otimes \underset{N\times 1} {\mathbf{z}} = 
\begin{cases}
\mathbf{0} &\text{then stop decoding}\\
\text{non-zero vector} &\text{then continue decoding}
\end{cases} \qquad (10)
$$

If the syndrome $\mathbf{s}$ is not the zero-vector decoding should be continued. Therefore, matrix $\mathbf{M}$ should be recalculated:

$$
M_{j,i} = \sum_{j'\epsilon A_i, j'\neq j} E_{j',i} + r_i \qquad (11)
$$

<img src="https://habrastorage.org/webt/nc/ub/vr/ncubvrajbvownowoxa0ulb_kpbq.png" width="500"/>

*Fig. 3. The illustration of the C2V message passing.*

> **NOTE #4:**
>
> The similar logic as in the **Note 2** and **3** can be applied:
> $$ M_{ij} = r_j - E_{ij} + \sum_{j} E_{ij} $$
> The same problems may occure.



After that the second iteration should follow. Idealy, we have to repeat iterations while $\mathbf{s}$ is a non-zero vector.

In [7]:
import numpy as np


class SPA:
    """ This class can apply SPA algorithm to received LLR vector r.
    
    Parameters
    ----------
    H: numpy.array
        Parity-Check matrix.
    Imax: int, optional
        Maximum number of iterations.
    trace_on: bool, optional
        To print or not to print intermediate results of calculations.
    
    Attributes
    ----------
    H: 2D numpy.array
        Parity-Check matrix.
    Imax: int
        Maximum number of iterations.
    trace_on: bool
        To print or not to print intermediate results of calculations.
    H_0: int
        Number of rows of the Parity-Check matrix.
    H_1: int
        Number of columns of the Parity-Check matrix.
    H_mirr: 2D numpy.array:
        'Mirror' of the Parity-Check matrix.
    """
    
    def __init__(self, H, Imax=1000, trace_on=True):
        self.H = H
        self.Imax = Imax
        self.trace_on = trace_on
        self.H_0 = np.shape(H)[0]
        self.H_1 = np.shape(H)[1]
        self.H_mirr = (self.H + np.ones(np.shape(self.H))) %2

    def __nrz(self, l):
        """Applies inverse NRZ 
        
        Parameters
        ----------
        l: 1D numpy.array
            LLR vector.
        
        Returns
        -------
        l: 1D numpy.array
            Mapped to binary symbols input vector.
        """
        
        for idx, l_j in enumerate(l):
            if l_j >= 0:
                l[idx] = 0
            else:
                l[idx] = 1
        return l

    def __calc_E(self, E, M):
        """ Calculates V2C message 
        
        Parameters
        ----------
        E: 2D numpy.array
            Current V2C matrix.
        M: 2D numpy.array
            Current C2V matrix.
        
        Returns
        -------
        E: 2D numpy.array
            Updated V2C matrix.
        """
        
        M = np.tanh(M / 2) + self.H_mirr
        for j in range(self.H_0):
            for i in range(self.H_1):
                if self.H[j,i] != 0:
                    E[j,i] = np.log(( 1 + np.prod(M[j,:]) \
                                     / M[j,i]) / ( 1 - np.prod(M[j,:]) / M[j,i]) )
        return E

    def __calc_M(self, M, E, r):
        """ Calculates C2V message 
        
        Parameters
        ----------
        M: 2D numpy.array
            Current C2V matrix.
        E: 2D numpy.array
            Current V2C matrix.
        r: 1D numpy.array
            Input LLR vector.
        
        Returns
        -------
        M: 2D numpy.array
            Updated C2V matrix.
        """
        
        for j in range(self.H_0):
            for i in range(self.H_1):
                if self.H[j,i] != 0:
                    M[j,i] = np.sum(E[:, i]) - E[j,i] + r[i]
        M = M*H 
        return M

    def decode(self, r):
        
        """Applies SPA algorithm to received LLR vector r.
    
        Parameters
        ----------
        r: numpy.array of floats
            received from demodulator LLR vector.
        
        Returns
        -------
        l: numpy.array
            Decoded message.

        """
        stop = False # stopping flag
        I = 0 # maximum number of iterations
        M = np.zeros(np.shape(H)) # C2V
        E = np.zeros(np.shape(H)) # V2C
        l = np.zeros(np.shape(r)) # LLR vector -> decoded message
        print('H:\n'+str(H))
        
        while stop == False and I != self.Imax:
            
            """ 1) Initial step """
            if I == 0:
                for j in range(np.shape(H)[0]):
                    M[j, :] = r*H[j, :]
            if self.trace_on == True:
                print('M:\n'+str(M))
            
            """ 2) V2C step """
            E = self.__calc_E(E, M)
            if self.trace_on == True:    
                print('E:\n'+str(E))
            
            """ 3) Decoded LLR vector """
            l = r + np.sum(E, axis=0)
            if self.trace_on == True:
                print('l:\n'+str(l))
            
            """ 4) NRZ mapping """
            l = self.__nrz(l)
            if self.trace_on == True:
                print('decoded:\n'+str(l))
            
            """ 5) Syndrom checking """
            s = np.dot(H, l) %2
            if np.prod(s == np.zeros(np.size(s))) == 1:
                stop = True
            else:
                I = I + 1
                M = self.__calc_M(M, E, r)
        return l

# Examples

Examples is provided according to [\[3, p.33\]](https://www.researchgate.net/publication/228977165_Introducing_Low-Density_Parity-Check_Codes).

Asume that: 
- \[0., 0., 1., 0., 1., 1.\] message was passed;
- r = \[−1.3863,1.3863,−1.3863,1.3863,−1.3863,−1.3863\] was received from demodulator;
- error in the first bit!

<img src="https://habrastorage.org/webt/aw/jj/_m/awjj_mpgjpak3qvjwqgtsklvods.jpeg" width="650" />


In [8]:
#Parity-check matrix (non-systematic form)
H = np.array([[1, 1, 0, 1, 0, 0], 
              [0, 1, 1, 0, 1, 0], 
              [1, 0, 0, 0, 1, 1], 
              [0, 0, 1, 1, 0, 1]]) # non-systematic case

# Received LLRs (the 1st bit is wrong - LDPC code should correct it):
r = np.array([-1.3863, 1.3863, -1.3863, 1.3863, -1.3863, -1.3863])

l = SPA(H).decode(r)
print('Decoded message:\n'+str(l))

H:
[[1 1 0 1 0 0]
 [0 1 1 0 1 0]
 [1 0 0 0 1 1]
 [0 0 1 1 0 1]]
M:
[[-1.3863  1.3863 -0.      1.3863 -0.     -0.    ]
 [-0.      1.3863 -1.3863  0.     -1.3863 -0.    ]
 [-1.3863  0.     -0.      0.     -1.3863 -1.3863]
 [-0.      0.     -1.3863  1.3863 -0.     -1.3863]]
E:
[[ 0.75377678 -0.75377678  0.         -0.75377678  0.          0.        ]
 [ 0.          0.75377678 -0.75377678  0.         -0.75377678  0.        ]
 [ 0.75377678  0.          0.          0.          0.75377678  0.75377678]
 [ 0.          0.         -0.75377678  0.75377678  0.         -0.75377678]]
l:
[ 0.12125356  1.3863     -2.89385356  1.3863     -1.3863     -1.3863    ]
decoded:
[0. 0. 1. 0. 1. 1.]
Decoded message:
[0. 0. 1. 0. 1. 1.]


It works!

Let's try another exemple [3, с.36 ]:
- the same Parity-Check matrx;
- code word is a = [0 0 1 0 1 1];
- received: y = [−0.5, 2.5, −4.0, 5.0, −3.5, 2.5].

<img src="https://habrastorage.org/webt/5-/mf/i5/5-mfi5eslpwp8ph5izhkfpypxgg.png" width="650"/>

In [9]:
r = np.array([-.5, 2.5, -4., 5., -3.5, 2.5])

l = SPA(H, trace_on=False).decode(r)
print('Decoded message:\n'+str(l))

H:
[[1 1 0 1 0 0]
 [0 1 1 0 1 0]
 [1 0 0 0 1 1]
 [0 0 1 1 0 1]]
Decoded message:
[0. 0. 1. 0. 1. 1.]


Well done!

## References

1. R.G. Gallager Low-Density Parity-Check Codes, IRE Transactions on Information Theory, 1962
2. D.J.C. MacKay Good Error-Correcting Codes Based on Very Sparse Matrices, IEEE Transactions on Information Theory, VOL.45, NO 2., March 1999
3. Johnson, S. J. (2006). Introducing low-density parity-check codes. University of Newcastle, Australia, V1.
4. Eroz M., Sun F. W., Lee L. N. DVB‐S2 low density parity check codes with near Shannon limit performance //International Journal of Satellite Communications and Networking. – 2004. – Т. 22. – №. 3. – С. 269-279.